"""Data model for strategy-layer attack hypotheses."""

from dataclasses import dataclass
from typing import List


@dataclass
class AttackVector:
    """
    Represents a single attack hypothesis generated by AI or heuristics.

    Attributes:
        vuln_class: Category of vulnerability (IDOR, SQLi, XSS, etc.)
        parameter: The specific parameter being targeted
        hypothesis: Human-readable explanation of the attack theory
        suggested_payloads: Concrete test values to try
        source: Where this came from ("ai" or "heuristic")
    """

    vuln_class: str
    parameter: str
    hypothesis: str
    suggested_payloads: List[str]
    source: str = "ai"
