"""
core/reporting/submission_render.py — Phase 6-PT2.

The renderer that produces SUBMISSION-GRADE markdown for HackerOne /
Bugcrowd / Intigriti. Distinct from BountyReport.to_markdown() — that's
the internal-audit-trail render with all the scoring metadata. THIS is
the version that goes to the triager.

Design principle: every line in the output must read as a researcher's
written work product. Zero scanner branding, zero internal labels,
zero "may be" hedging, zero auto-generated boilerplate.

Calibration target: Airtable's policy says "scanners, but please don't
copy-paste their output." This module is the operationalization of
"don't copy-paste scanner output" — we use scanner-assisted *discovery*
but the *artifact* the triager reads is verifiable from the operator's
captured exchanges alone.

────────────────────────────────────────────────────────────────────
Layout the triager reads (top-down):

  1. Title — specific impact-focused. NOT "Cross-Principal IDOR" but
     "Any authenticated user can read any other user's <resource>".

  2. TL;DR — 3 sentences. What's the bug, what's the impact, what's
     the access prerequisite. Triager decides in 10 seconds whether
     to keep reading. EVERYTHING ELSE IS OPTIONAL once they're hooked.

  3. Impact (concrete, quantified). Not OWASP boilerplate.

  4. Steps to Reproduce — the operator-captured exchanges, rendered
     by VC3 with persona attribution and placeholder legend.

  5. Suggested Remediation — specific to the bug class, with a
     framework hint when we can.

  6. References — CWE link only. No CVSS score in the artifact (it's
     a guess that hurts more than it helps for IDOR-class bugs the
     program scores themselves).

What's INTENTIONALLY ABSENT:
  * Sentinel branding / scan ID footer
  * Auto-scored CVSS with confidence caveats
  * Internal labels (signal, payload representation)
  * "Generated by" footer
  * Weasel phrasing ("may be", "could allow", "depending on context")
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


# ──────────────────────────── voice helpers ───────────────────────────


# Vuln-class-specific impact + remediation templates. Each is a small
# library of researcher-quality sentences. The renderer picks based
# on the finding's metadata. Generic fallbacks exist for unknown
# classes (low-quality fallback, not catastrophic).

_IMPACT_TEMPLATES = {
    "IDOR": (
        "Any authenticated account, regardless of role or tenant, can "
        "read another account's {resource_noun} by knowing or guessing "
        "its ID. The data exposed includes {data_examples}. With "
        "sequential or enumerable IDs, this is a full-tenant data "
        "disclosure."
    ),
    "SQLi": (
        "An unauthenticated request to {endpoint} executes attacker-"
        "controlled SQL against the production database. Depending on "
        "the database role, this allows arbitrary read or write across "
        "all tables — including credential and PII tables."
    ),
    "OPEN_REDIRECT": (
        "A redirect parameter in {endpoint} forwards browsers to "
        "attacker-controlled URLs without validation. Combined with "
        "the application's trusted appearance, this enables phishing "
        "campaigns that bypass standard URL-warning UX."
    ),
    "JWT_ALG_NONE": (
        "The application's JWT verification accepts tokens signed with "
        "`alg: none`, meaning an attacker can forge a token claiming "
        "any identity (including admin) without knowing the signing "
        "key. This is a complete authentication bypass."
    ),
    # Fallback for unknown classes — generic but not weasel-phrased.
    "_default": (
        "An attacker can {action} by sending a specific request to "
        "{endpoint}. The impact is direct and reproducible."
    ),
}

_REMEDIATION_TEMPLATES = {
    "IDOR": (
        "Add an ownership/membership check before returning the "
        "resource — `if resource.owner_id != current_user.id: raise "
        "Forbidden`. In ORM-backed code, scope the query to the "
        "current user's tenant (e.g. `Resource.where(account_id: "
        "current_user.account_id)`) so authorization is enforced by "
        "the data layer, not by post-load filtering. If the resource "
        "type supports shared-with-others semantics, replace direct "
        "object access with an explicit grants table."
    ),
    "SQLi": (
        "Replace string concatenation in the query with parameterized "
        "queries (your ORM's query builder will do this for you). "
        "Audit the codebase for any place where user-supplied values "
        "are interpolated into raw SQL; those are the candidates for "
        "the same class of bug."
    ),
    "OPEN_REDIRECT": (
        "Validate the redirect destination against an allowlist of "
        "trusted hosts (typically your own domain + a small set of "
        "known integration partners). Reject open external URLs."
    ),
    "JWT_ALG_NONE": (
        "Configure your JWT library to reject tokens whose header "
        "declares `alg: none` (or any algorithm other than the one "
        "you sign with). For most libraries this is a single config "
        "flag; in `jsonwebtoken` (Node) it's the `algorithms` "
        "allowlist argument; in `pyjwt` it's the `algorithms=` "
        "kwarg on `decode()`."
    ),
    "_default": (
        "Add server-side validation of the user-controlled input at "
        "the request boundary, before any data lookup or "
        "modification."
    ),
}


def _resource_noun_for_url(url: str) -> str:
    """Heuristic: pull a noun describing the affected resource from
    the URL path. /rest/basket/1 → 'basket'. /api/users/42 → 'user
    record'. Falls back to 'record' on ambiguity."""
    try:
        path = urlparse(url).path or ""
    except Exception:
        path = url
    parts = [p for p in path.split("/") if p and not p.isdigit()]
    if not parts:
        return "record"
    tail = parts[-1].lower().rstrip("s")  # singularize
    aliases = {
        "user": "user record",
        "basket": "basket",
        "order": "order",
        "profile": "profile",
        "account": "account",
        "invoice": "invoice",
        "subscription": "subscription",
        "session": "session",
        "ticket": "ticket",
    }
    return aliases.get(tail, tail)


def _data_examples_from_proof(proof: str) -> str:
    """Pick a few field names out of a JSON-ish proof body to make the
    impact sentence concrete. Returns 'this record's fields' fallback
    when we can't parse."""
    if not proof:
        return "the resource's fields"
    # Very conservative regex — pull out quoted JSON keys.
    import re
    keys = re.findall(r'"([A-Za-z_][A-Za-z0-9_]*)"\s*:', proof)
    interesting = [
        k for k in keys
        if k.lower() in {
            "email", "username", "id", "name", "phone", "address",
            "balance", "role", "permissions", "owner", "userid",
            "stripe_id", "token", "secret"
        }
    ]
    if interesting:
        # Distinct, in order, capped at 4
        seen = []
        for k in interesting:
            if k not in seen:
                seen.append(k)
            if len(seen) >= 4:
                break
        return ", ".join(f"`{k}`" for k in seen)
    return "the resource's fields"


# ──────────────────────────── classifier ──────────────────────────


def _canonicalize_vuln_class(report) -> str:
    """Map the finding's various class spellings to one of the
    template keys above. Falls back to '_default'."""
    md = getattr(report, "to_dict", lambda: {})().get("finding_id", "")
    # Look at multiple potential sources
    candidates: List[str] = []
    title = getattr(report, "title", "") or ""
    candidates.append(title.lower())
    type_text = getattr(report, "type", "") or ""
    candidates.append(type_text.lower())
    combined = " ".join(candidates)

    if any(s in combined for s in ("idor", "cross-principal", "cross_principal", "horizontal")):
        return "IDOR"
    if "sql" in combined:
        return "SQLi"
    if "open redirect" in combined or "open_redirect" in combined:
        return "OPEN_REDIRECT"
    if "jwt" in combined and "none" in combined:
        return "JWT_ALG_NONE"
    return "_default"


# ──────────────────────────── voice rules ──────────────────────────


# Phrases that scream "tool output". Every one of these gets STRIPPED
# from the report before output.
_BANNED_PHRASES = [
    # Weasel hedging that screams "tool wasn't sure":
    "may be present",
    "may affect",
    "could allow",
    "could lead to",
    "depending on the application context",
    # Internal Sentinel-isms:
    "(active verification)",
    "prompt remediation is recommended",
    "this finding covers",
    # Auto-scored CVSS caveats:
    "auto-scored",
    "low confidence",
    "manual review recommended",
    # Sentinel branding — must NEVER appear in submitted output:
    "sentinelforge",
    "sentinel forge",
    "generated by sentinel",
    "scan id:",
    "tool: vuln_verifier",
    "tool: sentinel",
]


def _strip_banned_phrases(text: str) -> str:
    """Remove every phrase that reads as boilerplate / tool-output.
    Operates case-insensitively. Whitespace cleanup at the end."""
    out = text
    lower = out.lower()
    for phrase in _BANNED_PHRASES:
        idx = lower.find(phrase)
        while idx != -1:
            out = out[:idx] + out[idx + len(phrase):]
            lower = out.lower()
            idx = lower.find(phrase)
    # Clean up doubled spaces / orphaned punctuation
    while "  " in out:
        out = out.replace("  ", " ")
    out = out.replace(" .", ".").replace(" ,", ",")
    return out.strip()


def _humanize_title(report) -> str:
    """Translate the BountyReport's title (which has tool jargon) into
    a triager-readable specific-impact title."""
    vuln_class = _canonicalize_vuln_class(report)
    target = getattr(report, "target", "") or getattr(report, "asset", "") or ""
    try:
        host = urlparse(target).netloc or "the application"
        path = urlparse(target).path or ""
    except Exception:
        host, path = "the application", ""

    if vuln_class == "IDOR":
        resource = _resource_noun_for_url(target)
        return (
            f"Any authenticated user can read any other user's "
            f"{resource} on {host}"
        )
    if vuln_class == "SQLi":
        return (
            f"Unauthenticated SQL injection in {host}{path} "
            f"(error-based)"
        )
    if vuln_class == "OPEN_REDIRECT":
        return f"Open redirect via {host}{path}"
    if vuln_class == "JWT_ALG_NONE":
        return f"JWT signature bypass via `alg: none` on {host}"
    # Fallback — keep the original title but strip the tool-jargon
    # parenthetical.
    raw = getattr(report, "title", "Finding")
    return _strip_banned_phrases(raw)


def _tldr_for(report) -> str:
    """Three-sentence TL;DR. The first sentence states the bug. The
    second states the impact. The third states the prerequisite (who
    can do this)."""
    vuln_class = _canonicalize_vuln_class(report)
    target = getattr(report, "target", "") or ""
    try:
        host = urlparse(target).netloc or "the application"
    except Exception:
        host = "the application"
    proof = getattr(report, "evidence", []) or []
    proof_text = "\n".join(proof) if proof else (getattr(report, "summary", "") or "")
    data_examples = _data_examples_from_proof(proof_text)

    if vuln_class == "IDOR":
        resource = _resource_noun_for_url(target)
        return (
            f"While reviewing {host}, I found that any authenticated "
            f"user can fetch any other user's {resource} by changing "
            f"the numeric ID in the request URL. The response includes "
            f"{data_examples} for the targeted user, which the "
            f"requesting user has no legitimate access to. Reproducing "
            f"the issue only requires an ordinary account; no admin "
            f"role or special role is needed."
        )
    if vuln_class == "SQLi":
        return (
            f"A request parameter on {host} is interpolated into a "
            f"SQL query without parameterization. Crafted input "
            f"produces a database-level error message that confirms "
            f"injection of arbitrary SQL fragments. No authentication "
            f"is required to reach the vulnerable endpoint."
        )
    if vuln_class == "OPEN_REDIRECT":
        return (
            f"A redirect parameter on {host} forwards browsers to "
            f"arbitrary external URLs without validation. The "
            f"redirect occurs in a trusted-looking application URL, "
            f"which is the high-value precondition for phishing. The "
            f"issue is reachable without authentication."
        )
    if vuln_class == "JWT_ALG_NONE":
        return (
            f"The application's JWT verification accepts tokens "
            f"declaring `alg: none`. An attacker can construct a "
            f"valid-looking token claiming any identity, including "
            f"admin, with no knowledge of the signing key. This is a "
            f"full authentication bypass."
        )
    # Fallback
    summary = getattr(report, "summary", "") or ""
    return _strip_banned_phrases(summary)[:600]


def _impact_for(report) -> str:
    vuln_class = _canonicalize_vuln_class(report)
    target = getattr(report, "target", "") or ""
    try:
        host = urlparse(target).netloc
    except Exception:
        host = ""
    try:
        endpoint = urlparse(target).path or ""
    except Exception:
        endpoint = target
    proof = "\n".join(getattr(report, "evidence", []) or [])
    template = _IMPACT_TEMPLATES.get(vuln_class, _IMPACT_TEMPLATES["_default"])
    return template.format(
        resource_noun=_resource_noun_for_url(target),
        data_examples=_data_examples_from_proof(proof),
        endpoint=endpoint or "the vulnerable endpoint",
        action="trigger the issue",
    )


def _remediation_for(report) -> str:
    vuln_class = _canonicalize_vuln_class(report)
    return _REMEDIATION_TEMPLATES.get(
        vuln_class, _REMEDIATION_TEMPLATES["_default"]
    )


def _references_for(report) -> List[str]:
    vuln_class = _canonicalize_vuln_class(report)
    # Map back to CWE IDs from the PT1 detection profile, but expressed
    # as triager-friendly inline references rather than a separate
    # "CWE" line.
    cwe_map = {
        "IDOR": ("CWE-639", "OWASP Top 10 A01:2021 — Broken Access Control"),
        "SQLi": ("CWE-89", "OWASP Top 10 A03:2021 — Injection"),
        "OPEN_REDIRECT": ("CWE-601", "OWASP ASVS V14.2.4"),
        "JWT_ALG_NONE": ("CWE-347", "RFC 7519 §6 — JWT signing requirements"),
    }
    if vuln_class in cwe_map:
        return list(cwe_map[vuln_class])
    return []


def _scope_of_testing(prov: Optional[Dict[str, Any]]) -> str:
    """A researcher-voice statement of testing scope + restraint, DERIVED from the
    recorded conduct but rendered as the researcher's own words.

    Deliberately NOT the branded provenance table (Merkle roots, capsule ids, "policy
    executor") — that reads as scanner output, which this renderer exists to avoid.
    Triagers ask "did you touch real data?" for access-control bugs; this answers it in
    plain prose and offers the verifiable log on request, without the tool smell."""
    if not prov or not prov.get("root"):
        return ""
    parts = ["All testing used accounts I registered and control."]
    reads = prov.get("cross_object_reads_2xx") or 0
    if reads == 1:
        parts.append("Confirming this required a single cross-account read of one object I "
                     "created in a second account I own; I did not enumerate or read any "
                     "other records.")
    elif reads > 1:
        parts.append(f"Confirming this required {reads} reads of objects I created in "
                     f"accounts I own.")
    if prov.get("owned_test_accounts_only") and not prov.get("destructive_actions_sent"):
        parts.append("No production or third-party data was accessed, and no destructive "
                     "actions were performed.")
    parts.append("A complete, timestamped request/response log of this testing is available "
                 "on request.")
    return " ".join(parts)


# ──────────────────────────── renderer ──────────────────────────


@dataclass
class SubmissionRender:
    """The submission-grade markdown + metadata.

    Distinct from BountyReport in that we DON'T carry the internal
    scoring + tool metadata. The output is what the triager reads,
    nothing more."""
    title: str
    tldr: str
    impact: str
    steps_to_reproduce: List[str]
    suggested_remediation: str
    references: List[str]
    markdown: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "tldr": self.tldr,
            "impact": self.impact,
            "steps_to_reproduce": list(self.steps_to_reproduce),
            "suggested_remediation": self.suggested_remediation,
            "references": list(self.references),
            "markdown": self.markdown,
        }


def render_for_submission(
    report,
    verify_steps: Optional[List[str]] = None,
    scope_provenance: Optional[Dict[str, Any]] = None,
) -> SubmissionRender:
    """Render a BountyReport as submission-grade markdown.

    Args:
      report: A BountyReport (or anything with .title, .summary,
        .severity, .target, .asset, .evidence — duck-typed for
        testability).
      verify_steps: List[str] of operator-verified repro steps from
        VC3. If provided, REPLACES whatever heuristic steps the
        BountyReport carried — operator verification always wins.

    Returns:
      SubmissionRender with .markdown ready for pasting into H1's
      report form.
    """
    title = _humanize_title(report)
    tldr = _tldr_for(report)
    impact = _impact_for(report)
    remediation = _remediation_for(report)
    references = _references_for(report)
    steps = verify_steps if verify_steps is not None else (
        getattr(report, "steps_to_reproduce", []) or []
    )

    # Strip banned phrases from EVERYTHING — including the operator's
    # repro steps. Defense-in-depth: even if the BountyReport carried
    # heuristic text with Sentinel branding, or the operator pasted
    # something Sentinel-generated into their notes, it shouldn't
    # land in the submission.
    impact = _strip_banned_phrases(impact)
    tldr = _strip_banned_phrases(tldr)
    title = _strip_banned_phrases(title)
    remediation = _strip_banned_phrases(remediation)
    steps = [_strip_banned_phrases(s) for s in steps]

    lines: List[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(tldr)
    lines.append("")
    lines.append("## Impact")
    lines.append("")
    lines.append(impact)
    lines.append("")
    lines.append("## Steps to Reproduce")
    lines.append("")
    if steps:
        for i, step_md in enumerate(steps, start=1):
            # Re-number cleanly. VC3's output already has 1-based
            # indices in the prose, but they're embedded in the body
            # text — adding a list prefix here keeps the markdown
            # tidy on platforms that auto-format numbered lists.
            lines.append(f"### {i}.")
            lines.append("")
            lines.append(step_md.strip())
            lines.append("")
    else:
        lines.append("_(Steps captured during verification — see attached evidence.)_")
        lines.append("")
    scope = _strip_banned_phrases(_scope_of_testing(scope_provenance))
    if scope:
        lines.append("## Scope of Testing")
        lines.append("")
        lines.append(scope)
        lines.append("")
    lines.append("## Suggested Remediation")
    lines.append("")
    lines.append(remediation)
    lines.append("")
    if references:
        lines.append("## References")
        lines.append("")
        for ref in references:
            lines.append(f"- {ref}")
        lines.append("")

    markdown = "\n".join(lines).strip() + "\n"

    return SubmissionRender(
        title=title,
        tldr=tldr,
        impact=impact,
        steps_to_reproduce=list(steps),
        suggested_remediation=remediation,
        references=references,
        markdown=markdown,
    )
