"""
scope_compiler — emit Sentinel's existing scope file format from a ProgramScope.

Output format (verified against ``core/server/routers/scans.py:265-281``):

  - One rule per line.
  - Lines starting with ``!`` are DENY rules; everything else is ALLOW.
  - The asset type is inferred at parse time from the line's shape — we
    don't need to emit any explicit type marker.
  - Lines starting with ``#`` are comments; blank lines are ignored.

  Examples:
      *.gitlab.com           # WILDCARD allow
      app.gitlab.com         # DOMAIN allow
      10.0.0.0/24            # CIDR allow
      !staging.example.com   # DOMAIN deny
      !*.internal.com        # WILDCARD deny

Why this is a separate file format and not just a Python data structure:

  Operators run Sentinel from the command line with ``--scope-file foo.txt``.
  The file is the human-editable artifact — they may want to review the
  ingested scope, tweak a rule, or version-control it before the scan
  fires. JSON would be denser but less hand-editable. The format mirrors
  ``scripts/lab/juice-shop-scope.txt`` exactly.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import List

from core.intel.program_scope import (
    ProgramScope,
    ScopeRule,
    ScopeRuleType,
)


# A small header block at the top of every emitted file. Lets the operator
# see at a glance what generated it, when, and from which source — and
# distinguishes auto-generated files from hand-edited ones, so they don't
# get clobbered by accident.
_HEADER_TEMPLATE = """\
# Scope file auto-generated by SentinelForge intel ingest.
#
# Program:       {name}
# Platform:      {platform}
# Handle:        {handle}
# Source URL:    {source_url}
# Generated:     {generated_at}
# Confidence:    {confidence:.2f}
# Schema:        sentinelforge-scope-v1
#
# Edit at your own risk — running `sentinel ingest` again will overwrite
# this file. Save edits separately if you want them to survive.
"""


def compile_scope_file(scope: ProgramScope) -> str:
    """Render a ``ProgramScope`` as the textual scope file format.

    Returns the file content as a single string. The caller is responsible
    for writing it to disk (the compiler is pure for testability).

    Rule ordering: in-scope rules first, then out-of-scope (deny). Within
    each block, rules are emitted in the order they appear in
    ``scope.scope_rules`` — preserves the operator's mental model of
    "primary scope, exceptions follow."
    """
    lines: List[str] = []
    lines.append(_render_header(scope))

    in_scope = [r for r in scope.scope_rules if r.in_scope]
    out_of_scope = [r for r in scope.scope_rules if not r.in_scope]

    if in_scope:
        lines.append("# ─── In-scope ───")
        for rule in in_scope:
            rendered = _render_rule(rule, allow=True)
            if rendered is not None:
                lines.append(rendered)
        lines.append("")

    if out_of_scope:
        lines.append("# ─── Out-of-scope (deny overrides allow on conflict) ───")
        for rule in out_of_scope:
            rendered = _render_rule(rule, allow=False)
            if rendered is not None:
                lines.append(rendered)
        lines.append("")

    if not in_scope and not out_of_scope:
        # An empty scope file is legal but useless; emit a clear comment
        # so the operator can see they need to fix it before scanning.
        lines.append("# ⚠ No scope rules were extracted from the policy.")
        lines.append("# This file will not allow any targets to be scanned.")
        lines.append("# Add at least one in-scope rule, e.g.:  *.example.com")
        lines.append("")

    return "\n".join(lines)


# ─────────────────────────── Internals ─────────────────────────────

def _render_header(scope: ProgramScope) -> str:
    return _HEADER_TEMPLATE.format(
        name=scope.name,
        platform=scope.platform.value,
        handle=scope.handle or "(none)",
        source_url=scope.source_url,
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        confidence=scope.extraction_confidence,
    )


def _render_rule(rule: ScopeRule, *, allow: bool) -> str | None:
    """Render a single ``ScopeRule`` as a line of the scope file.

    Returns ``None`` for unsupported rule types (e.g. MOBILE_APP,
    SOURCE_CODE) — those aren't network targets so the scope-file format
    has no way to represent them. The operator sees them in the
    ``ProgramScope`` JSON; they just don't make it into the scan scope.
    """
    pattern = rule.pattern.strip()
    if not pattern:
        return None

    # Asset-type-specific rendering. The renderer mirrors the parser at
    # core/server/routers/scans.py:268-281 — if we emit a line that
    # parses to a different asset_type than we intended, the scope check
    # silently goes wrong. The cross-reference is intentional.
    if rule.rule_type == ScopeRuleType.DOMAIN:
        line = pattern
        # Defensive: if the pattern looks like a wildcard despite being
        # tagged DOMAIN, render it consistently so the loader sees it as
        # wildcard. Same for any leading-digit + slash pattern (CIDR).
        # This avoids round-trip mismatches.
    elif rule.rule_type == ScopeRuleType.IP_CIDR:
        line = pattern
    elif rule.rule_type == ScopeRuleType.URL:
        line = pattern  # URL rules contain "://"; loader infers URL type.
    else:
        # MOBILE_APP, SOURCE_CODE, OTHER — not representable in the
        # text scope file format. Drop with a comment so the operator
        # sees why.
        return f"# (skipped — {rule.rule_type.value} not representable in scope file: {pattern})"

    if not allow:
        line = "!" + line

    # Append the optional notes as an inline comment for operator clarity.
    if rule.notes:
        # Trim very long notes so the file stays readable.
        note_text = rule.notes if len(rule.notes) <= 80 else rule.notes[:77] + "..."
        line = f"{line}  # {note_text}"

    return line
