"""
Phase 6-PT2 tests for core/reporting/submission_render.py.

The critical correctness properties this file pins:

  1. NONE of the banned scanner-output phrases appear in the rendered
     markdown. The list is in submission_render._BANNED_PHRASES. If
     any of these escape into a submitted report, the triager flags
     it as automated tool output.

  2. The title is impact-focused (not class-jargon-focused). "Cross-
     Principal IDOR (active verification)" never appears as a title;
     "Any authenticated user can read any other user's ..." does.

  3. The TL;DR is researcher-narrative voice. First-person observation,
     concrete impact, prerequisite stated. No weasel hedging.

  4. The repro steps come from the VC3 output when provided —
     operator-verified always wins over heuristic.

  5. There's no Sentinel branding in the output (no "Generated by",
     no scan ID, no tool name).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import pytest

from core.reporting.submission_render import (
    _BANNED_PHRASES,
    _canonicalize_vuln_class,
    _strip_banned_phrases,
    render_for_submission,
)


@dataclass
class _FakeReport:
    """Stand-in for BountyReport. Only the fields render_for_submission
    actually reads."""
    title: str = "Finding"
    summary: str = ""
    type: str = ""
    severity: str = "HIGH"
    target: str = ""
    asset: str = ""
    steps_to_reproduce: List[str] = field(default_factory=list)
    evidence: List[str] = field(default_factory=list)


# ───────────────────────── banned-phrase stripping ─────────────────────────


class TestBannedPhrases:
    def test_every_banned_phrase_is_stripped(self):
        for phrase in _BANNED_PHRASES:
            text = f"prelude. {phrase}. postlude."
            stripped = _strip_banned_phrases(text)
            assert phrase not in stripped.lower(), (
                f"banned phrase {phrase!r} survived stripping"
            )

    def test_case_insensitive(self):
        text = "A high severity vulnerability MAY BE PRESENT here."
        stripped = _strip_banned_phrases(text)
        assert "may be present" not in stripped.lower()
        assert "MAY BE PRESENT" not in stripped

    def test_double_space_cleaned(self):
        """When we strip a phrase mid-sentence, the leftover spaces
        get cleaned up so output reads naturally."""
        stripped = _strip_banned_phrases("foo may be present bar")
        # No double-spaces in output.
        assert "  " not in stripped


# ───────────────────────── vuln-class canonicalization ─────────────────────────


class TestVulnClassCanonicalization:
    def test_idor_recognized_from_title(self):
        r = _FakeReport(title="Cross-Principal IDOR on /api/users/42")
        assert _canonicalize_vuln_class(r) == "IDOR"

    def test_idor_recognized_from_type(self):
        r = _FakeReport(type="Horizontal IDOR (active verification)")
        assert _canonicalize_vuln_class(r) == "IDOR"

    def test_sqli_recognized(self):
        r = _FakeReport(title="Error-based SQL injection in /search")
        assert _canonicalize_vuln_class(r) == "SQLi"

    def test_open_redirect_recognized(self):
        r = _FakeReport(title="Open Redirect via ?next param")
        assert _canonicalize_vuln_class(r) == "OPEN_REDIRECT"

    def test_jwt_alg_none_recognized(self):
        r = _FakeReport(title="JWT alg:none bypass on /auth")
        assert _canonicalize_vuln_class(r) == "JWT_ALG_NONE"

    def test_unknown_class_falls_back_to_default(self):
        r = _FakeReport(title="Something weird")
        assert _canonicalize_vuln_class(r) == "_default"


# ───────────────────────── title rewriting ─────────────────────────


class TestTitleRewriting:
    def test_idor_title_is_impact_focused(self):
        r = _FakeReport(
            title="[High] Cross-Principal IDOR (active verification) in /api/users/42",
            target="https://api.example.com/api/users/42",
            asset="https://api.example.com/api/users/42",
        )
        rendered = render_for_submission(r)
        # Title says what the bug DOES, not what it's CALLED.
        assert "any authenticated user can read" in rendered.title.lower()
        # And mentions the host so the triager can match scope.
        assert "api.example.com" in rendered.title

    def test_title_strips_active_verification_parenthetical(self):
        """No internal Sentinel labels in the output."""
        r = _FakeReport(
            title="[High] Cross-Principal IDOR (active verification)",
            target="https://app.example/api/foo/1",
            asset="https://app.example/api/foo/1",
        )
        rendered = render_for_submission(r)
        assert "(active verification)" not in rendered.markdown
        assert "(active verification)" not in rendered.title


# ───────────────────────── TL;DR voice ─────────────────────────


class TestTLDRVoice:
    def test_idor_tldr_uses_researcher_voice(self):
        r = _FakeReport(
            title="Cross-Principal IDOR",
            target="https://api.example.com/api/users/42",
            asset="https://api.example.com/api/users/42",
            evidence=['{"id":42,"email":"victim@example.com","role":"user"}'],
        )
        rendered = render_for_submission(r)
        # First-person observation.
        assert "while reviewing" in rendered.tldr.lower() or \
               "i found" in rendered.tldr.lower() or \
               "i noticed" in rendered.tldr.lower()
        # Concrete impact mentions the target host.
        assert "api.example.com" in rendered.tldr.lower()
        # And surfaces real data field names from the evidence.
        assert "`email`" in rendered.tldr or "`id`" in rendered.tldr

    def test_tldr_avoids_weasel_phrasing(self):
        r = _FakeReport(
            title="IDOR",
            summary="A high severity vulnerability may be present in /api/users/42",
            target="https://example.com/api/users/42",
            asset="https://example.com/api/users/42",
        )
        rendered = render_for_submission(r)
        for weasel in (
            "may be present", "may affect", "could allow",
            "depending on the application context",
        ):
            assert weasel not in rendered.markdown.lower(), (
                f"weasel phrase {weasel!r} leaked into submission markdown"
            )


# ───────────────────────── repro steps ─────────────────────────


class TestRepoSteps:
    def test_verify_steps_replace_heuristic_steps(self):
        """When operator provides VC3-generated repro, that wins —
        the BountyReport's heuristic steps are ignored."""
        verify_steps = [
            "As user `alice`, send `GET /api/users/2` — server returns HTTP 200 with bob's data.",
        ]
        r = _FakeReport(
            title="IDOR",
            target="http://h/api/users/2",
            asset="http://h/api/users/2",
            steps_to_reproduce=["DO NOT USE - heuristic step"],  # should NOT appear
        )
        rendered = render_for_submission(r, verify_steps=verify_steps)
        assert "DO NOT USE" not in rendered.markdown
        assert "As user `alice`" in rendered.markdown

    def test_no_verify_steps_falls_back_to_report_steps(self):
        r = _FakeReport(
            title="IDOR",
            target="http://h/api/users/2",
            asset="http://h/api/users/2",
            steps_to_reproduce=["Step 1: do X.", "Step 2: do Y."],
        )
        rendered = render_for_submission(r)  # no verify_steps arg
        assert "Step 1: do X." in rendered.markdown


# ───────────────────────── no Sentinel branding ─────────────────────────


class TestNoBranding:
    def test_no_sentinelforge_in_output(self):
        r = _FakeReport(
            title="Cross-Principal IDOR (active verification)",
            target="http://h/api/users/42",
            asset="http://h/api/users/42",
            steps_to_reproduce=["Generated by SentinelForge — do step X"],
        )
        rendered = render_for_submission(r)
        assert "sentinelforge" not in rendered.markdown.lower()
        assert "scan id" not in rendered.markdown.lower()

    def test_no_tool_label(self):
        r = _FakeReport(
            title="IDOR",
            target="http://h/api/users/42",
            asset="http://h/api/users/42",
        )
        rendered = render_for_submission(r)
        # No "Tool: vuln_verifier" line.
        assert "vuln_verifier" not in rendered.markdown.lower()
        assert "tool:" not in rendered.markdown.lower()

    def test_no_cvss_score_or_confidence_caveats(self):
        r = _FakeReport(
            title="IDOR",
            target="http://h/api/users/42",
            asset="http://h/api/users/42",
        )
        rendered = render_for_submission(r)
        # No auto-scored CVSS, no confidence caveats.
        assert "auto-scored" not in rendered.markdown.lower()
        assert "low confidence" not in rendered.markdown.lower()


# ───────────────────────── overall shape ─────────────────────────


class TestRenderShape:
    def test_markdown_has_required_sections(self):
        r = _FakeReport(
            title="Cross-Principal IDOR",
            target="https://app.example/api/users/42",
            asset="https://app.example/api/users/42",
        )
        rendered = render_for_submission(r)
        md = rendered.markdown
        for section in ("## Summary", "## Impact", "## Steps to Reproduce",
                        "## Suggested Remediation"):
            assert section in md, f"missing section: {section}"

    def test_references_present_for_known_class(self):
        r = _FakeReport(
            title="Cross-Principal IDOR",
            target="https://app.example/api/users/42",
            asset="https://app.example/api/users/42",
        )
        rendered = render_for_submission(r)
        # IDOR carries CWE-639 reference.
        assert "CWE-639" in rendered.markdown
        # And OWASP A01.
        assert "Broken Access Control" in rendered.markdown

    def test_to_dict_round_trips_via_json(self):
        import json
        r = _FakeReport(
            title="IDOR",
            target="http://h/api/users/42",
            asset="http://h/api/users/42",
        )
        rendered = render_for_submission(r)
        d = rendered.to_dict()
        json.dumps(d)  # must not raise
        assert "markdown" in d
        assert "tldr" in d
        assert "title" in d


# ───────────────────────── Scope of Testing (restraint) ────────────────────

class TestScopeOfTesting:
    def _prov(self, **kw):
        base = {"root": "ec384e6a", "cross_object_reads_2xx": 1,
                "destructive_actions_sent": 0, "owned_test_accounts_only": True}
        base.update(kw)
        return base

    def test_scope_section_rendered_from_provenance(self):
        r = _FakeReport(title="IDOR", type="IDOR", target="https://x.com")
        md = render_for_submission(r, scope_provenance=self._prov()).markdown
        assert "## Scope of Testing" in md
        assert "accounts I registered and control" in md
        assert "single cross-account read" in md
        assert "no destructive actions were performed" in md.lower()
        assert "available on request" in md

    def test_scope_section_stays_in_researcher_voice_no_branding(self):
        # The whole point: substance without the scanner-output smell.
        r = _FakeReport(title="IDOR", type="IDOR")
        md = render_for_submission(r, scope_provenance=self._prov()).markdown.lower()
        for smell in ("sentinel", "merkle", "capsule", "provenance root", "policy executor",
                      "scan_capsule", "sha256"):
            assert smell not in md

    def test_no_scope_section_without_provenance(self):
        r = _FakeReport(title="IDOR", type="IDOR")
        assert "Scope of Testing" not in render_for_submission(r).markdown
        assert "Scope of Testing" not in render_for_submission(r, scope_provenance={"events": 0}).markdown

    def test_restraint_claim_omitted_if_conduct_does_not_support_it(self):
        # Don't claim "no production data" unless owned-only AND nothing destructive.
        r = _FakeReport(title="IDOR", type="IDOR")
        md = render_for_submission(r, scope_provenance=self._prov(owned_test_accounts_only=False)).markdown
        assert "## Scope of Testing" in md
        assert "no production or third-party data was accessed" not in md.lower()
